### ISSUE TITLE
Purchase.completed is true when it shouldnt

### ISSUE THREAD

**Issue by JordinKee** [cozycodegh/cordova-plugin-inapppurchases#10]
First of all, thanks for this plugin!

I noticed odd behavior of my app after I upgraded this plugin from 2.4.8 to 3.0.2. Going through the commits, I noticed this line: 

`completed: res.pending == 0,`

at https://github.com/cozycodegh/cordova-plugin-inapppurchases/commit/0bc203cd0cf83d036a759a7c12acf17d8d1e33cf#diff-f03cc1bc99555771d580b62c075ca39d17dffbdd8498c73b84d584c1ca83feebR245

Every purchase I make in my app is now flagged 'completed', even though in fact they're not (once a purchase is successful, it needs to be completed manually to unlock the product in case of a consumable).

All in all, I think that line should be:

`completed: res.completed == 1,`

**Comment by cozycodegh** [comment]
Hi Jordin,

Thanks for pointing that out! Some of the code from the iOS version was accidentally copied into the Android version. The plugin version 3.0.3 will show the correct values when calling `inapppurchases.purchase` for completed, pending, and verified now.
