### ISSUE TITLE
Guidance: How to use the pluging with typescript + webpack?

### ISSUE THREAD

**Issue by maloneyg** [cozycodegh/cordova-plugin-inapppurchases#13]
Do you have some guidance on how to use this plugin with typescript + webpack?  I've done the following:

- included the npm package in package.json: `"cordova-plugin-inapppurchases": "^3.1.1",`
- added the plugin to config.xml: `<plugin name="cordova-plugin-inapppurchases" spec="^3.1.1" />`
- installed the plugin from the command line during the build process: `cordova plugin add "cordova-plugin-inapppurchases" && \`

But I get the following error in my console logs when I invoke `inAppPurchases.getAllProductInfo`:

```
ReferenceError: inAppPurchases is not defined
```

**Comment by cozycodegh** [comment]
I haven't used webpack or typescript, so I'm not sure what's going wrong. 

You added it to the cordova project, and it should be there when you type `cordova plugin list`, but it's not available in the javascript for some reason.

**Comment by maloneyg** [comment]
I believe the issue was actually with Svelte, which I'm also using.  The solution here has made cordova plugins available to me:
https://stackoverflow.com/a/63580844
