### ISSUE TITLE
inAppPurchases.restorePurchases() get Network connection lost.

### ISSUE THREAD

**Issue by bmg1** [cozycodegh/cordova-plugin-inapppurchases#14]
hi!

cordova 12.0.0 (cordova-lib@12.0.1)

 "cordova-ios": "^7.1.1",

Plugins:
    "cordova-plugin-inappbrowser": "^6.0.0",
    "cordova-plugin-inapppurchases": "^3.1.1",
    "cordova-plugin-network-information": "^3.0.0",

I use restore purchise with button:

`//this function use for click evvent

function onRestoreButtonPressOrUpdate(){

    inAppPurchases.restorePurchases().then( function(purchases){

        for (var i=0; i<purchases.length; i++){

            if (purchases[i]["pending"]) continue;
            if (!purchases[i]["completed"]){

                inAppPurchases
                    .completePurchase(purchases[i]["productId"])
                    .catch(function(err){

                    });
            }

            addPremium(purchases[i]);
       
        }
    }).catch (function(err){
        // view or handle billing or api error messages
        

    });
}`

But get error(catch : "Network connection lost."

How i can restore purchise?

thanks

**Comment by cozycodegh** [comment]
Hi Vladimir,

It can't restore purchases when the phone isn't connected to the internet. You could tell them to try to again later because an error occurred.

**Comment by cozycodegh** [comment]
Good luck with the app!
If that doesn't solve it, please re-open the issue.
