### ISSUE TITLE
Plans for Upgrading to Google Play Billing Library v6 or v7?

### ISSUE THREAD

**Issue by bmg1** [cozycodegh/cordova-plugin-inapppurchases#15]
First, thank you for this great plugin! I’ve been using it for several years now, and it has always performed reliably.

Currently, the plugin uses Google Play Billing Library v5, which will be deprecated by 1st November 2024. Given this, I am planning to upgrade it in the coming months. Additionally, Google released v7 of their Billing Library last week: https://developer.android.com/google/play/billing/release-notes.

I am wondering if there are plans to update this plugin to work with either v6 or v7. I haven't seen any information or discussions about these versions, so I thought it best to ask directly.

Thank you for your attention.

**Comment by cozycodegh** [comment]
No problem!
The plugin should be at Android Billing Library 7 for Google Play since version v.3.1.1.
See here to update the plugin: https://cozycode.ca/post?pon=cordova-plugin-inapppurchases
You can find the version of the plugin you have with `cordova plugin list`
