### ISSUE TITLE
In app purchases on iOS are not displayed

### ISSUE THREAD

**Issue by marcellov7** [cozycodegh/cordova-plugin-inapppurchases#16]
Hi
Granted that in some previous version everything worked correctly, but on iOS now the in app purchases no longer appear;

Has something changed?
ios vs 16.6.1

arrayProductIapIds is a valid array ids.

```

inAppPurchases.getAllProductInfo(arrayProductIapIds).then(function (products) {
                    console.log(JSON.stringify(products));  //iOS return always [], Android is ok
                    ....
```

**Comment by marcellov7** [comment]
After analyzing, it seems that the problem comes from using in app purchase and subscription at the same time, is it not possible to mix?

**Comment by cozycodegh** [comment]
I just did some tests and have not reproduced the issue.
The plugin can probably only do one transaction at a time, the first should complete before the next. It is fine to have in app purchases and subscriptions in the same app, there should be no problem there.

Could it be a problem with the settings within the app store?

**Comment by marcellov7** [comment]
> I just did some tests and have not reproduced the issue. The plugin can probably only do one transaction at a time, the first should complete before the next. It is fine to have in app purchases and subscriptions in the same app, there should be no problem there.
> 
> Could it be a problem with the settings within the app store?

I'm going crazy, but I'm not getting out of it.
I'll let you know what it depends on.

ps: I sent you an email from your site, if you have time to help me it would be greatly appreciated :D
Thanks

**Comment by cozycodegh** [comment]
Yes, it gets tricky. No problem, can help with app debugging there
