### ISSUE TITLE
com.android.billingclient.api.ProxyBillingActivity.onCreate

### ISSUE THREAD

**Issue by marcellov7** [cozycodegh/cordova-plugin-inapppurchases#17]
Hi,
what can this crash on android depend on?
Thanks

OS version: android9
Model:Galaxy S20+ 5G

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.IntentSender android.app.PendingIntent.getIntentSender()' on a null object reference

`com.android.billingclient.api.ProxyBillingActivity.onCreate (com.android.billingclient:billing@@7.0.0:14)
android.app.Activity.performCreate (Activity.java:7144)
android.app.Activity.performCreate (Activity.java:7135)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1271)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2931)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3086)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1816)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6718)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)`

**Comment by cozycodegh** [comment]
This is a crash in the Android billing library that is outside of the plugin. Did it come up from logs of user crashes? I see some people get this error rarely from just using the Android billing library, some kind of bug with the library.
