### ISSUE TITLE
Error message formatting

### ISSUE THREAD

**Issue by orestis-z** [cozycodegh/cordova-plugin-inapppurchases#2]
Would it be possible to improve the error message formatting?

Currently it looks like this:

```json
{"code":-4,
 "message":"UNKNOWN_ERROR InAppBilling Error",
 "iabText": "Billing response error: A user billing error occurred during processing. Google Play In-app Billing API version is less than 3Error checking for billing v5 support.",
 "responseCode":3,
 "iabCode":-4}
```

I'd like to show to the end user what the error is.

E.g. both `iabText` and `message` seem to consist of two or more concatenated strings (e.g. `"Billing response error: A user billing error occurred during processing. Google Play In-app Billing API version is less than 3"` and `"Error checking for billing v5 support."`). Is it possible to keep them separate in the error response?

**Comment by cozycodegh** [comment]
Put in the time to sort out the error messages… Now on Android, there’s a separate responseCode which matches the Google Play Billing library and a responseMessage that Google Play returns. 
This page says how to get the latest version of the plugin in an app:
https://cozycode.ca/post?pon=cordova-plugin-inapppurchases

**Comment by orestis-z** [comment]
Great thanks a lot! 🎊

**Comment by cozycodegh** [comment]
:)
