### ISSUE TITLE
Inconsistent response from getAllProductInfo

### ISSUE THREAD

**Issue by orestis-z** [cozycodegh/cordova-plugin-inapppurchases#4]
When requesting product info for subscriptions I'm getting an inconsistent response (see screenshots below). I've noticed this issue in the older packages (cordova-plugin-inapppurchase without the "s") as well. Maybe some response caching is going on?

![image](https://user-images.githubusercontent.com/23146389/218254993-675f0c32-2514-4b6d-9210-fcf63d55e3f9.png)

and

![image](https://user-images.githubusercontent.com/23146389/218255182-ae9dcaff-b7ea-4e80-bde5-5d5113a916bf.png)

**Comment by cozycodegh** [comment]
Are you looking to get a list of details on all of the available subscriptions to get the price after the trial? I can add that to list of updates to make next.

With this response, it should subscribe you to the plan including the free trial.

**Comment by orestis-z** [comment]
I think your last suggestions seems appropriate 👍

**Comment by cozycodegh** [comment]
Updated the billing query, now the newest version returns only the queried products in Android as expected as well.

**Comment by orestis-z** [comment]
Great thanks a lot!

**Comment by cozycodegh** [comment]
Thanks :)
