### ISSUE TITLE
Struggling to implement plugin into ionic app

### ISSUE THREAD

**Issue by AlexisDelevallee** [cozycodegh/cordova-plugin-inapppurchases#5]
Hi Cozycodegh, thanks for your plugin.

I need help to use into ionic cordova application.

What should I do ?

**Comment by cozycodegh** [comment]
Hey Alexis,
I don’t have experience with iconic, but if there’s a command line, you can add the plugin with: `cordova plugin add cordova-plugin-inapppurchases`. Then you should be able to use the plugin in the app’s javascript.

**Comment by cozycodegh** [comment]
Seems like you can add the plugin with the `ionic` in front of the command: `ionic cordova plugin add cordova-plugin-inapppurchases`

**Comment by cozycodegh** [comment]
That should get started for using the plugin in ionic.
