### ISSUE TITLE
inAppPurchases.purchase promise not resolving nor throwing

### ISSUE THREAD

**Issue by orestis-z** [cozycodegh/cordova-plugin-inapppurchases#6]
<img width="1252" alt="Screenshot 2023-10-14 at 18 57 12" src="https://github.com/cozycodegh/cordova-plugin-inapppurchases/assets/23146389/6a4227b6-30b2-4530-b3b8-c2235e03a549">

or

<img width="1343" alt="Screenshot 2023-10-14 at 19 12 27" src="https://github.com/cozycodegh/cordova-plugin-inapppurchases/assets/23146389/4ef9c2c5-8b27-4ee7-af5b-adba03a1d728">

In some situations (e.g. as in the screenshots above) the `Promise` created by `inAppPurchases.purchase(product_id)` does not resolve nor throw an error. This is problematic since I can't handle it on the javascript side.

**Comment by cozycodegh** [comment]
Hi orestis-z,
We updated the plugin to have some more logging on failures. Can you send the new log output?

**Comment by orestis-z** [comment]
Hello @cozycodegh, it was an error on my side thus I had closed it! Sorry for the confusion 🙏
